{% set name = "pyvisgraph" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b7c6895d9e00ed7771e3db187fb079a236616adfc20abbbb97aefe43de54e990

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - tqdm >=4.23.4

test:
  imports:
    - pyvisgraph
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/TaipanRex/pyvisgraph
  summary: 'Given a set of simple obstacle polygons, build a visibility graph and find the shortest path between two points.'
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/TaipanRex/pyvisgraph

extra:
  recipe-maintainers:
    - moorepants
